### ISSUE TITLE
Re-authenticate when cookie has expired

### ISSUE THREAD

**Issue by flimzy** [go-kivik/couchdb#124] opened 2018-09-07 12:06 UTC
There is currently no mechanism in place to re-authenticate once a cookie has expired.

Adding this probably means adding a client-configurable "refresh" interval, since there is no way to tell from the server how long a session is likely to last (short of reading server config--which should generally require admin access).

**Comment by ComaVN** [comment] 2019-05-06 16:09
For anyone else being bitten by this, the Q&D fix for this is in [the wiki](https://github.com/go-kivik/kivik/wiki/Authentication):
```go
client, err := kivik.New("couch", "http://localhost:5984")
if err != nil {
    panic(err)
}
err := client.Authenticate(couchdb.BasicAuth("admin", "abc123"))
```

**Comment by fungiboletus** [comment] 2020-03-26 11:24
Looks like I got bitten hard by it.

So if I understand well:

- I can continue to use the credentials in the connection DSN but I need to do a request regularly to maintain the session active.
- Or I can use HTTP BasicAuth all the time and not use the sessions.

What's the best in your opinion ?

**Comment by flimzy** [comment] 2020-03-26 11:27
Basic auth would be the easiest, but it is less efficient. I will try to spend some time coming up with a solution to this soon. It's been sitting around for far too long.

**Comment by fungiboletus** [comment] 2020-03-26 11:32
Great. Weanwhile I will see if doing a `.Stats(context.TODO())` every 30s will prevent the issue.

**Comment by flimzy** [comment] 2020-03-26 11:33
Let me know.  30s may be overkill (unless you have a very short server timeout). Default I think is usually 10m.

**Comment by fungiboletus** [comment] 2020-03-27 09:22
Yes I confirm the default is 10 minutes. This strategy worked until my laptop went to sleep for the night. The token was obviously expired this morning.

It wasn't so much a problem before because my local couchdb for development didn't have a password, but now with Couchdb 3.0.0 you must have a password. And for production that have a password… I got saved because I query CouchDB in the health check endpoint of my API and Kubernetes queries it regularly.

**Comment by fungiboletus** [comment] 2020-03-27 10:15
So I came up with the _beautiful_ following code. It's far from perfect because it will have a broken kivik database for up to 60 seconds if the program wasn't able to refresh the token in time (breakpoint, sleeping computer, no network link to couchdb), but it's an improvement.

```golang

// It's a global variable
var database *kivik.DB

func keepCouchDBSessionAlive() {
	timer := time.Tick(time.Minute)
	for range timer {
		_, err := database.Stats(context.Background())
		if err != nil {
			switch kivik.StatusCode(err) {
			case kivik.StatusUnauthorized:
				fmt.Fprintln(os.Stderr, "Session may have expired.")
				configureDatabase()
			default:
				fmt.Fprintf(os.Stderr, "Database keep alive error: %s\n", err)
			}
		}
	}
}

func main() {

    ...
    
    configureDatabase()
    go keepCouchDBSessionAlive()

    ...
    
}
```

**Closed** 2020-03-29 13:57 UTC

**Comment by flimzy** [comment] 2020-03-29 14:08
@fungiboletus I have just published v3.0.1 of this package which I believe fixes this for any server that sets the expiration time of the cookie.

Fixing it for servers that are not configured to include the expiration time will require an API change, so would not be nearly as easy.

Can you install 3.0.1 and let me know if it solves the problem for you?

**Comment by fungiboletus** [comment] 2020-03-30 07:58
Great ! The fix looks a lot more beautiful than what I did.

Unfortunately I just realized that I'm still on the version 1.8.1. I will upgrade to version 3.0.1 hopefully in a few weeks. But thanks a lot for your work.

**Comment by fungiboletus** [comment] 2020-04-13 07:29
I confirm the problem is solved for me 🙂

**Comment by flimzy** [comment] 2020-04-13 07:49
> I confirm the problem is solved for me

Great, I'm glad to hear it! Thanks for getting back to me.
